[workspace]
resolver = "3"
members = ["crates/mlib-spec", "crates/mediagram", "crates/mediagram-tmdb", "crates/mediagram-core"]

[workspace.package]
version = "0.23.2"
edition = "2024"
license = "MIT"
rust-version = "1.87"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"
sha2 = "0.10"
hex = "0.4"
ulid = "1"
thiserror = "2"
